# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: akshaypranavkalathil/portfolio-email
  tag: e08b28e01b9bcef6d1478f8784ec5b5dfca440f4
