apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-email
spec:
  replicas: 3
  selector:
    matchLabels:
      app: portfolio-email # Add this label
  template:
    metadata:
      labels:
        app: portfolio-email
    spec:
      containers:
        - name: portfolio-email
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          ports:
            - containerPort: 8080
