version: '3'

services:
  app:
    image: oven/bun
    working_dir: /app
    environment:
      NODE_ENV: production
    command: ['bun', 'src/index.ts']
    ports:
      - '3000:3000'
    volumes:
      - .:/app

  bun1:
    image: oven/bun
    working_dir: /app
    environment:
      NODE_ENV: production
    command: ['bun', 'src/index.ts']
    ports:
      - '3001:3000'
    volumes:
      - .:/app

  bun2:
    image: oven/bun
    working_dir: /app
    environment:
      NODE_ENV: production
    command: ['bun', 'src/index.ts']
    ports:
      - '3002:3000'
    volumes:
      - .:/app

  bun3:
    image: oven/bun
    working_dir: /app
    environment:
      NODE_ENV: production
    command: ['bun', 'src/index.ts']
    ports:
      - '3003:3000'
    volumes:
      - .:/app

  bun4:
    image: oven/bun
    working_dir: /app
    environment:
      NODE_ENV: production
    command: ['bun', 'src/index.ts']
    ports:
      - '3004:3000'
    volumes:
      - .:/app

  bun5:
    image: oven/bun
    working_dir: /app
    environment:
      NODE_ENV: production
    command: ['bun', 'src/index.ts']
    ports:
      - '3005:3000'
    volumes:
      - .:/app

  bun6:
    image: oven/bun
    working_dir: /app
    environment:
      NODE_ENV: production
    command: ['bun', 'src/index.ts']
    ports:
      - '3006:3000'
    volumes:
      - .:/app

  bun7:
    image: oven/bun
    working_dir: /app
    environment:
      NODE_ENV: production
    command: ['bun', 'src/index.ts']
    ports:
      - '3007:3000'
    volumes:
      - .:/app

  bun8:
    image: oven/bun
    working_dir: /app
    environment:
      NODE_ENV: production
    command: ['bun', 'src/index.ts']
    ports:
      - '3008:3000'
    volumes:
      - .:/app

  bun9:
    image: oven/bun
    working_dir: /app
    environment:
      NODE_ENV: production
    command: ['bun', 'src/index.ts']
    ports:
      - '3009:3000'
    volumes:
      - .:/app

  bun10:
    image: oven/bun
    working_dir: /app
    environment:
      NODE_ENV: production
    command: ['bun', 'src/index.ts']
    ports:
      - '3010:3000'
    volumes:
      - .:/app

  bun11:
    image: oven/bun
    working_dir: /app
    environment:
      NODE_ENV: production
    command: ['bun', 'src/index.ts']
    ports:
      - '3011:3000'
    volumes:
      - .:/app

  bun12:
    image: oven/bun
    working_dir: /app
    environment:
      NODE_ENV: production
    command: ['bun', 'src/index.ts']
    ports:
      - '3012:3000'
    volumes:
      - .:/app
